apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-core-secrets
  namespace: bikeshare-dev-ns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secrets-manager-store
    kind: ClusterSecretStore
  target:
    name: airflow-core-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: bikeshare/airflow/core