[project]
name = "bikeshare-analytics-pipeline"
version = "0.1.0"
description = ""
authors = [
    {name = "peteradekolu@gmail.com"}
]
license = {text = "'"}
readme = "README.md"
requires-python = ">=3.10,<3.14"
dependencies = [
    "pandas (==2.2.3)",
    "requests (>=2.32.5,<3.0.0)",
    "dbt-snowflake (==1.9.0)",
    "dbt-core (>=1.11.7,<2.0.0)",
    "boto3 (>=1.40.33,<2.0.0)",
    "pyarrow (>=21.0.0,<22.0.0)",
    "configparser (>=7.2.0,<8.0.0)",
    "great-expectations (==0.18.21)",
    "sqlalchemy (>=1.4.0,<2.0.0)",
    "snowflake-sqlalchemy (>=1.7.7,<2.0.0)",
    "slack-sdk (>=3.38.0,<4.0.0)",
    "pytest (>=9.0.1,<10.0.0)",
    "moto (>=5.1.17,<6.0.0)",
    "matplotlib (>=3.10.8,<4.0.0)",
    "werkzeug (>=2.3.0,<3.0.0)",
    "s3fs (>=2026.1.0,<2027.0.0)",
    "pytest-cov (>=7.0.0,<8.0.0)",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
