name: 'dbt_transform'
version: '1.0.0'
profile: 'dbt_bikeshare_profile'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:        
  - "target"
  - "dbt_packages"
models:
  dbt_transform:
    dims:
      materialized: table
    fct:
      materialized: table