name: Deploy to Development

on:
  push:
    branches: [feat/deploy-k8]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read 

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # - name: Debug OIDC token
      #   run: |
      #     TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com")
      #     echo $TOKEN | python3 -c "import sys,json,base64; token=json.load(sys.stdin)['value']; payload=token.split('.')[1]; print(json.loads(base64.b64decode(payload + '==').decode()))"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::356315793531:role/github-actions-role
          aws-region: us-east-1
      
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
      
      - name: Install Helm
        uses: azure/setup-helm@v3
      
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name bikeshare-dev-cluster --region us-east-1
      
      - name: Test cluster connection
        run: |
          kubectl config view
          kubectl get nodes
      

      - name: Install External Secrets Operator
        run: |
          helm repo add external-secrets https://charts.external-secrets.io
          helm repo update
          helm upgrade --install external-secrets external-secrets/external-secrets \
            --namespace external-secrets \
            --create-namespace \
            --wait
      
      - name: Wait for CRDs to be ready
        run: |
          kubectl wait --for=condition=established --timeout=60s \
            crd/clustersecretstores.external-secrets.io \
            crd/externalsecrets.external-secrets.io
          sleep 10
      
      - name: Check service account
        run: |
          kubectl get serviceaccount -n external-secrets

      - name: Apply ClusterSecretStore
        run: kubectl apply -f kubernetes/cluster-secret-store.yaml

      - name: Apply ExternalSecrets
        run: |
          kubectl apply -f kubernetes/external-secrets/airflow-core-external-secret.yaml
          kubectl apply -f kubernetes/external-secrets/dbt-snowflake-external-secret.yaml
      
      - name: Wait for ExternalSecrets to sync
        run: |
          kubectl wait externalsecret airflow-core-secrets \
            --for=condition=Ready \
            --timeout=60s \
            --namespace bikeshare-dev-ns
          kubectl wait externalsecret bikeshare-dbt-secrets \
            --for=condition=Ready \
            --timeout=60s \
            --namespace bikeshare-dev-ns

      - name: Deploy Airflow via Helm
        run: |
          helm repo add apache-airflow https://airflow.apache.org
          helm repo update
          helm upgrade --install airflow apache-airflow/airflow \
            --version 3.7.1 \
            -f kubernetes/dev-values.yaml \
            --namespace bikeshare-dev-ns \
            --set images.airflow.repository=docker.io/savepeter2/bikeshare-pipeline \
            --set images.airflow.tag=dev \
            --create-namespace \
            --wait      

      - name: Sync DAGs to S3
        run: |
          aws s3 sync ./dags/ s3://bikeshare-pipeline-dev/dags/ \
            --delete --exclude "*.pyc" --exclude "__pycache__/*"
      
      # - name: Run smoke tests
      #   run: poetry run pytest tests/e2e/smoke_tests.py

      - name: Notify Slack
        if: success() || failure()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: "bikeshare_analytics_alerts"  
          slack-message: |
            *Bikeshare Pipeline Deploy* ${{ job.status == 'success' && '✅' || '❌' }}
            *Branch:* ${{ github.ref_name }}
            *Commit:* ${{ github.sha }}
            *Status:* ${{ job.status }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_OAUTH_TOKEN }}